[build]
  command = "npm install && npm run build"
  publish = ".next"
  base = "dreamlayer"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs", "react", "react-dom", "next", "@metaplex-foundation/js", "@solana/web3.js", "@reown/appkit"]
  included_files = ["node_modules/styled-jsx/**/*", "node_modules/styled-jsx/style.js", "node_modules/styled-jsx/dist/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 