[build]
command = "cd dreamlayer && npm install && npm run build"
publish = "dreamlayer/.next"
base = "."

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20.18.0"

[[plugins]]
package = "@netlify/plugin-nextjs"