import { cookieStorage, createStorage } from 'wagmi';
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi';
import { mainnet, arbitrum } from '@reown/appkit/networks';
import type { Chain } from 'viem';
import { createAppKit } from '@reown/appkit/react';

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID;

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local');
}

// Define supported networks
export const networks: [Chain, ...Chain[]] = [mainnet, arbitrum];

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;

// Initialize AppKit
export function initializeAppKit() {
  if (!projectId) {
    console.error('AppKit Initialization Error: Project ID is missing.');
    return;
  }

  createAppKit({
    adapters: [wagmiAdapter],
    projectId,
    networks,
    defaultNetwork: mainnet,
    metadata: {
      name: 'DreamLayer',
      description: 'DreamLayer - Digital Dreams Network',
      url: typeof window !== 'undefined' ? window.location.origin : 'https://dreamlayer.io',
      icons: ['https://dreamlayer.io/icon.png'],
    },
    features: { analytics: true },
  });
}
